### ISSUE TITLE
代码块的指针颜色难以看清

### ISSUE THREAD

**Issue by fjchen7** [luili/newgithub-for-Typora#1]
在黑色背景色下难以辨别。

**Comment by luili** [comment]
@jimusichen 确实有这个问题，可以自行修改。我一般都是贴完代码块换行后才会展示效果，写的时候是 Markdown 倒是还好。

**Comment by fjchen7** [comment]
嗯，我对比了其他的 css 样式做了修改。

```
.cm-s-inner .CodeMirror-cursor {
	border-left: 1px solid #f8f8f0;
}
```

**Comment by fjchen7** [comment]
此外，文件里说css是从 https://github.com/GitbookIO/gitbook fork过来的，但我在里面没有找到原始样式。

**Comment by luili** [comment]
@jimusichen 其实我是拿 Typora 默认的 Github 样式修改的，对于原作者 fork 的来源并没有考证，刚看了下，可能是 gitbook 内容的样式，可以打开任意一篇内容查看下。
